// Code generated by gowsdl DO NOT EDIT.

package workDocuments

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

//
// Restrição:Tipos de Documento (GR-Guia de remessa, GT-Guia de transporte, GA-Guia de movimentação de ativos próprios,GC-Guia de consignação, GD-Guia ou nota de devolução afetuada pelo cliente.
//

type MovementType string

const (
	MovementTypeGR MovementType = "GR"

	MovementTypeGT MovementType = "GT"

	MovementTypeGA MovementType = "GA"

	MovementTypeGC MovementType = "GC"

	MovementTypeGD MovementType = "GD"
)

type SAFPTtextTypeMandatoryMax210Car string

type SAFPTtextTypeMandatoryMax200Car string

type SAFPTtextTypeMandatoryMax100Car string

type SAFPTtextTypeMandatoryMax60Car string

type SAFPTtextTypeMandatoryMax50Car string

type SAFPTtextTypeMandatoryMax32Car string

type SAFPTtextTypeMandatoryMax20Car string

type SAFdateType soap.XSDDate

type SAFdecimalType float64

type SAFmonetaryType float64

type SAFPTPortugueseVatNumber int32

type SAFdateTimeType soap.XSDDateTime

// N para Normal, T para Por conta de terceiros, A para Documento anulado

type MovementStatus string

const (
	MovementStatusN MovementStatus = "N"

	MovementStatusT MovementStatus = "T"

	MovementStatusA MovementStatus = "A"
)

type DocumentNumber string

type PostalCodePT string

type EnvioDocumentoTransporteRequestElem StockMovement

type EnvioDocumentoTransporteResponseElem StockMovementResponse

type StockMovement struct {
	XMLName xml.Name `xml:"https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/ envioDocumentoTransporteRequestElem"`

	TaxRegistrationNumber *SAFPTPortugueseVatNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	CompanyName *SAFPTtextTypeMandatoryMax100Car `xml:"CompanyName,omitempty" json:"CompanyName,omitempty"`

	CompanyAddress *AddressStructurePT `xml:"CompanyAddress,omitempty" json:"CompanyAddress,omitempty"`

	DocumentNumber *SAFPTtextTypeMandatoryMax60Car `xml:"DocumentNumber,omitempty" json:"DocumentNumber,omitempty"`

	ATCUD *SAFPTtextTypeMandatoryMax100Car `xml:"ATCUD,omitempty" json:"ATCUD,omitempty"`

	ATDocCodeID *SAFPTtextTypeMandatoryMax200Car `xml:"ATDocCodeID,omitempty" json:"ATDocCodeID,omitempty"`

	MovementStatus *MovementStatus `xml:"MovementStatus,omitempty" json:"MovementStatus,omitempty"`

	MovementDate *SAFdateType `xml:"MovementDate,omitempty" json:"MovementDate,omitempty"`

	MovementType *MovementType `xml:"MovementType,omitempty" json:"MovementType,omitempty"`

	// CustomerTaxID and SupplierTaxID must appear before customer details and Line items.
	// Exactly one of these must be filled in (AT validation rule).
	// Note: gowsdl generated these after Line which is wrong — fixed manually.
	CustomerTaxID *SAFPTtextTypeMandatoryMax20Car `xml:"CustomerTaxID,omitempty" json:"CustomerTaxID,omitempty"`

	SupplierTaxID *SAFPTtextTypeMandatoryMax20Car `xml:"SupplierTaxID,omitempty" json:"SupplierTaxID,omitempty"`

	CustomerAddress *AddressStructurePT `xml:"CustomerAddress,omitempty" json:"CustomerAddress,omitempty"`

	CustomerName *SAFPTtextTypeMandatoryMax100Car `xml:"CustomerName,omitempty" json:"CustomerName,omitempty"`

	AddressTo *AddressStructurePT `xml:"AddressTo,omitempty" json:"AddressTo,omitempty"`

	AddressFrom *AddressStructurePT `xml:"AddressFrom,omitempty" json:"AddressFrom,omitempty"`

	MovementEndTime *SAFdateTimeType `xml:"MovementEndTime,omitempty" json:"MovementEndTime,omitempty"`

	MovementStartTime *SAFdateTimeType `xml:"MovementStartTime,omitempty" json:"MovementStartTime,omitempty"`

	VehicleID *SAFPTtextTypeMandatoryMax32Car `xml:"VehicleID,omitempty" json:"VehicleID,omitempty"`

	Line []*Line `xml:"Line,omitempty" json:"Line,omitempty"`
}

type StockMovementResponse struct {
	XMLName xml.Name `xml:"https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/ envioDocumentoTransporteResponseElem"`

	ResponseStatus []*ResponseStatus `xml:"ResponseStatus,omitempty" json:"ResponseStatus,omitempty"`

	DocumentNumber *SAFPTtextTypeMandatoryMax60Car `xml:"DocumentNumber,omitempty" json:"DocumentNumber,omitempty"`

	ATCUD *SAFPTtextTypeMandatoryMax100Car `xml:"ATCUD,omitempty" json:"ATCUD,omitempty"`

	ATDocCodeID *SAFPTtextTypeMandatoryMax200Car `xml:"ATDocCodeID,omitempty" json:"ATDocCodeID,omitempty"`
}

type ResponseStatus struct {
	ReturnCode int32 `xml:"ReturnCode,omitempty" json:"ReturnCode,omitempty"`

	ReturnMessage string `xml:"ReturnMessage,omitempty" json:"ReturnMessage,omitempty"`
}

type Line struct {
	OrderReferences []*OrderReferences `xml:"OrderReferences,omitempty" json:"OrderReferences,omitempty"`

	ProductDescription *SAFPTtextTypeMandatoryMax200Car `xml:"ProductDescription,omitempty" json:"ProductDescription,omitempty"`

	Quantity *SAFdecimalType `xml:"Quantity,omitempty" json:"Quantity,omitempty"`

	UnitOfMeasure *SAFPTtextTypeMandatoryMax20Car `xml:"UnitOfMeasure,omitempty" json:"UnitOfMeasure,omitempty"`

	UnitPrice *SAFmonetaryType `xml:"UnitPrice,omitempty" json:"UnitPrice,omitempty"`
}

type OrderReferences struct {
	OriginatingON *SAFPTtextTypeMandatoryMax60Car `xml:"OriginatingON,omitempty" json:"OriginatingON,omitempty"`
}

type AddressStructurePT struct {
	Addressdetail *SAFPTtextTypeMandatoryMax210Car `xml:"Addressdetail,omitempty" json:"Addressdetail,omitempty"`

	City *SAFPTtextTypeMandatoryMax50Car `xml:"City,omitempty" json:"City,omitempty"`

	PostalCode *PostalCodePT `xml:"PostalCode,omitempty" json:"PostalCode,omitempty"`

	Country string `xml:"Country,omitempty" json:"Country,omitempty"`
}

type DocumentosTransporte interface {
	EnvioDocumentoTransporte(request *StockMovement) (*StockMovementResponse, error)

	EnvioDocumentoTransporteContext(ctx context.Context, request *StockMovement) (*StockMovementResponse, error)
}

type documentosTransporte struct {
	client *soap.Client
}

func NewDocumentosTransporte(client *soap.Client) DocumentosTransporte {
	return &documentosTransporte{
		client: client,
	}
}

func (service *documentosTransporte) EnvioDocumentoTransporteContext(ctx context.Context, request *StockMovement) (*StockMovementResponse, error) {
	response := new(StockMovementResponse)
	err := service.client.CallContext(ctx, "https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *documentosTransporte) EnvioDocumentoTransporte(request *StockMovement) (*StockMovementResponse, error) {
	return service.EnvioDocumentoTransporteContext(
		context.Background(),
		request,
	)
}
