// Code generated by gowsdl DO NOT EDIT.

package types

import (
	"context"
	"encoding/xml"
	"time"

	"github.com/hooklift/gowsdl/soap"
	"github.com/shopspring/decimal"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

// Campo para indicacao da mais recente versao do
// SAF-T
// que consegue criar
// o software que processa as faturas
// e
// comunica por
// webservice.

type AuditFileVersion string

// Versao do webservice.

type EFaturaMDVersion string

type SAFPTPortugueseVatNumber int32

type SAFPTtextTypeMandatoryMax20Car string

type SAFPTtextTypeMandatoryMax30Car string

type SAFPTtextTypeMandatoryMax60Car string

type SAFPTtextTypeMandatoryMax100Car string

type DocumentNumber string

type HashCharacters string

// Restricao: Tipos de Documento fatura (FT - Fatura,
// NC-Nota de
// Credito, ND - Nota de Debito, FS - Fatura Simplificada, FR
// - Fatura-recibo).
// Para o setor Segurador (a), ainda pode ser
// preenchido com: RP para
// Premio ou
// recibo de premio, RE para Estorno ou
// recibo de estorno, CS para Imputacao
// a
// co-seguradoras, LD para
// Imputacao a co-seguradora lider, RA para Resseguro
// aceite. (a) Para
// os dados ate 2019-12-31.

type InvoiceTypeType string

const (
	InvoiceTypeTypeFT InvoiceTypeType = "FT"

	InvoiceTypeTypeNC InvoiceTypeType = "NC"

	InvoiceTypeTypeND InvoiceTypeType = "ND"

	InvoiceTypeTypeFS InvoiceTypeType = "FS"

	InvoiceTypeTypeFR InvoiceTypeType = "FR"

	InvoiceTypeTypeRP InvoiceTypeType = "RP"

	InvoiceTypeTypeRE InvoiceTypeType = "RE"

	InvoiceTypeTypeCS InvoiceTypeType = "CS"

	InvoiceTypeTypeLD InvoiceTypeType = "LD"

	InvoiceTypeTypeRA InvoiceTypeType = "RA"
)

// Deve ser preenchido com: CM Consultas de mesa; CC
// Credito de
// consignacao; FC Fatura de consignacao nos termos do art 38
// do codigo do IVA;
// FO Folhas de obra; NE Nota de Encomenda; OU Outros;
// OR Orcamentos; PF
// Proforma.
// Para o setor Segurador, ainda pode ser
// preenchido
// com: RP para Premio ou recibo de premio, RE para Estorno
// ou recibo de
// estorno, CS para Imputacao a co-seguradoras, LD para
// Imputacao a
// co-seguradora lider, RA para Resseguro aceite.

type WorkTypeType string

const (
	WorkTypeTypeCM WorkTypeType = "CM"

	WorkTypeTypeCC WorkTypeType = "CC"

	WorkTypeTypeFC WorkTypeType = "FC"

	WorkTypeTypeFO WorkTypeType = "FO"

	WorkTypeTypeNE WorkTypeType = "NE"

	WorkTypeTypeOU WorkTypeType = "OU"

	WorkTypeTypeOR WorkTypeType = "OR"

	WorkTypeTypePF WorkTypeType = "PF"

	WorkTypeTypeRP WorkTypeType = "RP"

	WorkTypeTypeRE WorkTypeType = "RE"

	WorkTypeTypeCS WorkTypeType = "CS"

	WorkTypeTypeLD WorkTypeType = "LD"

	WorkTypeTypeRA WorkTypeType = "RA"
)

// Deve ser preenchido com: RC Recibo emitido no ambito
// do regime de
// IVA de Caixa (incluindo os relativos a adiantamentos
// desse
// regime)

type PaymentTypeType string

const (
	PaymentTypeTypeRC PaymentTypeType = "RC"
)

// D para Débito, C para Crédito

type DebitCreditIndicator string

const (
	DebitCreditIndicatorD DebitCreditIndicator = "D"

	DebitCreditIndicatorC DebitCreditIndicator = "C"
)

type EACCode string

type SelfBillingIndicator int32

const (
	SelfBillingIndicator0 SelfBillingIndicator = 0

	SelfBillingIndicator1 SelfBillingIndicator = 1
)

type CashVATSchemeIndicator int32

type PaperLessIndicator int32

type TaxIDCountry string

// Elemento do SAF-T alterado, com a inclusão do valor
// máximo permitido.

type MonetaryType decimal.Decimal

type TaxType string

const (
	TaxTypeIVA TaxType = "IVA"

	TaxTypeIS TaxType = "IS"

	TaxTypeNS TaxType = "NS"
)

type TaxCountryRegion string

type TaxCode string

type PercentageType decimal.Decimal

type TaxExemptionCode string

type RegisterInvoiceRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterInvoiceRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	AuditFileVersion *AuditFileVersion `xml:"AuditFileVersion,omitempty" json:"AuditFileVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	TaxEntity *TaxEntity `xml:"TaxEntity,omitempty" json:"TaxEntity,omitempty"`

	SoftwareCertificateNumber *SoftwareCertificateNumber `xml:"SoftwareCertificateNumber,omitempty" json:"SoftwareCertificateNumber,omitempty"`

	InvoiceData *InvoiceDataType `xml:"InvoiceData,omitempty" json:"InvoiceData,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type ChangeInvoiceStatusRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangeInvoiceStatusRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	InvoiceHeader *InvoiceHeaderType `xml:"InvoiceHeader,omitempty" json:"InvoiceHeader,omitempty"`

	InvoiceStatus *NewInvoiceStatusType `xml:"InvoiceStatus,omitempty" json:"InvoiceStatus,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type DeleteInvoiceRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeleteInvoiceRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	Reason string `xml:"reason,omitempty" json:"reason,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`

	DocumentsList *ListInvoiceDocumentsType `xml:"documentsList,omitempty" json:"documentsList,omitempty"`

	DateRange *DateRangeType `xml:"dateRange,omitempty" json:"dateRange,omitempty"`
}

type RegisterInvoiceResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterInvoiceResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type ChangeInvoiceStatusResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangeInvoiceStatusResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type DeleteInvoiceResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeleteInvoiceResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type RegisterWorkRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterWorkRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	AuditFileVersion *AuditFileVersion `xml:"AuditFileVersion,omitempty" json:"AuditFileVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	TaxEntity *TaxEntity `xml:"TaxEntity,omitempty" json:"TaxEntity,omitempty"`

	SoftwareCertificateNumber *SoftwareCertificateNumber `xml:"SoftwareCertificateNumber,omitempty" json:"SoftwareCertificateNumber,omitempty"`

	WorkData *WorkDataType `xml:"WorkData,omitempty" json:"WorkData,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type ChangeWorkStatusRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangeWorkStatusRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	WorkHeader *WorkHeaderType `xml:"WorkHeader,omitempty" json:"WorkHeader,omitempty"`

	WorkStatus *NewWorkStatusType `xml:"WorkStatus,omitempty" json:"WorkStatus,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type DeleteWorkRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeleteWorkRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	Reason string `xml:"reason,omitempty" json:"reason,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`

	DocumentsList *ListWorkDocumentsType `xml:"documentsList,omitempty" json:"documentsList,omitempty"`

	DateRange *DateRangeType `xml:"dateRange,omitempty" json:"dateRange,omitempty"`
}

type ChangeWorkStatusResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangeWorkStatusResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type DeleteWorkResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeleteWorkResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type RegisterWorkResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterWorkResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type RegisterPaymentRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterPaymentRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	AuditFileVersion *AuditFileVersion `xml:"AuditFileVersion,omitempty" json:"AuditFileVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	TaxEntity *TaxEntity `xml:"TaxEntity,omitempty" json:"TaxEntity,omitempty"`

	SoftwareCertificateNumber *SoftwareCertificateNumber `xml:"SoftwareCertificateNumber,omitempty" json:"SoftwareCertificateNumber,omitempty"`

	PaymentData *PaymentDataType `xml:"PaymentData,omitempty" json:"PaymentData,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type ChangePaymentStatusRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangePaymentStatusRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	PaymentHeader *PaymentHeaderType `xml:"PaymentHeader,omitempty" json:"PaymentHeader,omitempty"`

	PaymentStatus *NewPaymentStatusType `xml:"PaymentStatus,omitempty" json:"PaymentStatus,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`
}

type DeletePaymentRequest struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeletePaymentRequest"`

	EFaturaMDVersion *EFaturaMDVersion `xml:"eFaturaMDVersion,omitempty" json:"eFaturaMDVersion,omitempty"`

	TaxRegistrationNumber *TaxRegistrationNumber `xml:"TaxRegistrationNumber,omitempty" json:"TaxRegistrationNumber,omitempty"`

	Reason string `xml:"reason,omitempty" json:"reason,omitempty"`

	CanalRegisto *ChannelType `xml:"CanalRegisto,omitempty" json:"CanalRegisto,omitempty"`

	DocumentsList *ListPaymentDocumentsType `xml:"documentsList,omitempty" json:"documentsList,omitempty"`

	DateRange *DateRangeType `xml:"dateRange,omitempty" json:"dateRange,omitempty"`
}

type RegisterPaymentResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents RegisterPaymentResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type ChangePaymentStatusResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents ChangePaymentStatusResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type DeletePaymentResponse struct {
	XMLName xml.Name `xml:"http://factemi.at.min_financas.pt/documents DeletePaymentResponse"`

	Response *ResponseType `xml:"Response,omitempty" json:"Response,omitempty"`
}

type NonNegativeInteger int32

type InvoiceNo SAFPTtextTypeMandatoryMax60Car

type PaymentRefNo SAFPTtextTypeMandatoryMax60Car

type TaxRegistrationNumber SAFPTPortugueseVatNumber

type TaxEntity SAFPTtextTypeMandatoryMax20Car

type SoftwareCertificateNumber NonNegativeInteger

type ATCUD SAFPTtextTypeMandatoryMax100Car

type InvoiceDate time.Time

type InvoiceType InvoiceTypeType

type TransactionDate time.Time

type PaymentType PaymentTypeType

type WorkDate time.Time

type WorkType WorkTypeType

type SystemEntryDate time.Time

type CustomerTaxID SAFPTtextTypeMandatoryMax30Car

type CustomerTaxIDCountry TaxIDCountry

type OriginatingON SAFPTtextTypeMandatoryMax60Car

type TaxPointDate time.Time

type Reference SAFPTtextTypeMandatoryMax60Car

type TotalTaxBase MonetaryType

type Amount MonetaryType

type InvoiceHeaderType struct {
	InvoiceNo *InvoiceNo `xml:"InvoiceNo,omitempty" json:"InvoiceNo,omitempty"`

	ATCUD *ATCUD `xml:"ATCUD,omitempty" json:"ATCUD,omitempty"`

	InvoiceDate *InvoiceDate `xml:"InvoiceDate,omitempty" json:"InvoiceDate,omitempty"`

	InvoiceType *InvoiceType `xml:"InvoiceType,omitempty" json:"InvoiceType,omitempty"`

	SelfBillingIndicator *SelfBillingIndicator `xml:"SelfBillingIndicator,omitempty" json:"SelfBillingIndicator,omitempty"`

	CustomerTaxID *CustomerTaxID `xml:"CustomerTaxID,omitempty" json:"CustomerTaxID,omitempty"`

	CustomerTaxIDCountry *CustomerTaxIDCountry `xml:"CustomerTaxIDCountry,omitempty" json:"CustomerTaxIDCountry,omitempty"`
}

type InvoiceDataType struct {
	*InvoiceHeaderType

	DocumentStatus *InvoiceStatus `xml:"DocumentStatus,omitempty" json:"DocumentStatus,omitempty"`

	HashCharacters *HashCharacters `xml:"HashCharacters,omitempty" json:"HashCharacters,omitempty"`

	CashVATSchemeIndicator *CashVATSchemeIndicator `xml:"CashVATSchemeIndicator,omitempty" json:"CashVATSchemeIndicator,omitempty"`

	PaperLessIndicator *PaperLessIndicator `xml:"PaperLessIndicator,omitempty" json:"PaperLessIndicator,omitempty"`

	EACCode *EACCode `xml:"EACCode,omitempty" json:"EACCode,omitempty"`

	SystemEntryDate *SystemEntryDate `xml:"SystemEntryDate,omitempty" json:"SystemEntryDate,omitempty"`

	LineSummary []LineSummary `xml:"LineSummary,omitempty" json:"LineSummary,omitempty"`

	DocumentTotals *DocumentTotals `xml:"DocumentTotals,omitempty" json:"DocumentTotals,omitempty"`

	WithholdingTax []*WithholdingTax `xml:"WithholdingTax,omitempty" json:"WithholdingTax,omitempty"`
}

type WorkHeaderType struct {
	DocumentNumber *DocumentNumber `xml:"DocumentNumber,omitempty" json:"DocumentNumber,omitempty"`

	ATCUD *ATCUD `xml:"ATCUD,omitempty" json:"ATCUD,omitempty"`

	WorkDate *WorkDate `xml:"WorkDate,omitempty" json:"WorkDate,omitempty"`

	WorkType *WorkType `xml:"WorkType,omitempty" json:"WorkType,omitempty"`

	CustomerTaxID *CustomerTaxID `xml:"CustomerTaxID,omitempty" json:"CustomerTaxID,omitempty"`

	CustomerTaxIDCountry *CustomerTaxIDCountry `xml:"CustomerTaxIDCountry,omitempty" json:"CustomerTaxIDCountry,omitempty"`
}

type WorkDataType struct {
	*WorkHeaderType

	DocumentStatus *WorkStatus `xml:"DocumentStatus,omitempty" json:"DocumentStatus,omitempty"`

	HashCharacters *HashCharacters `xml:"HashCharacters,omitempty" json:"HashCharacters,omitempty"`

	EACCode *EACCode `xml:"EACCode,omitempty" json:"EACCode,omitempty"`

	SystemEntryDate *SystemEntryDate `xml:"SystemEntryDate,omitempty" json:"SystemEntryDate,omitempty"`

	LineSummary []LineSummary `xml:"LineSummary,omitempty" json:"LineSummary,omitempty"`

	DocumentTotals *DocumentTotals `xml:"DocumentTotals,omitempty" json:"DocumentTotals,omitempty"`
}

type PaymentHeaderType struct {
	PaymentRefNo *PaymentRefNo `xml:"PaymentRefNo,omitempty" json:"PaymentRefNo,omitempty"`

	ATCUD *ATCUD `xml:"ATCUD,omitempty" json:"ATCUD,omitempty"`

	TransactionDate *TransactionDate `xml:"TransactionDate,omitempty" json:"TransactionDate,omitempty"`

	PaymentType *PaymentType `xml:"PaymentType,omitempty" json:"PaymentType,omitempty"`

	CustomerTaxID *CustomerTaxID `xml:"CustomerTaxID,omitempty" json:"CustomerTaxID,omitempty"`

	CustomerTaxIDCountry *CustomerTaxIDCountry `xml:"CustomerTaxIDCountry,omitempty" json:"CustomerTaxIDCountry,omitempty"`
}

type PaymentDataType struct {
	*PaymentHeaderType

	DocumentStatus *PaymentStatus `xml:"DocumentStatus,omitempty" json:"DocumentStatus,omitempty"`

	SystemEntryDate *SystemEntryDate `xml:"SystemEntryDate,omitempty" json:"SystemEntryDate,omitempty"`

	LineSummary []struct {
		SourceDocumentID []*SourceDocumentID `xml:"SourceDocumentID,omitempty" json:"SourceDocumentID,omitempty"`

		SettlementAmount *MonetaryType `xml:"SettlementAmount,omitempty" json:"SettlementAmount,omitempty"`

		DebitCreditIndicator *DebitCreditIndicator `xml:"DebitCreditIndicator,omitempty" json:"DebitCreditIndicator,omitempty"`

		Tax *Tax `xml:"Tax,omitempty" json:"Tax,omitempty"`

		TaxExemptionCode *TaxExemptionCode `xml:"TaxExemptionCode,omitempty" json:"TaxExemptionCode,omitempty"`

		Amount *Amount `xml:"Amount,omitempty" json:"Amount,omitempty"`
	} `xml:"LineSummary,omitempty" json:"LineSummary,omitempty"`

	DocumentTotals *DocumentTotals `xml:"DocumentTotals,omitempty" json:"DocumentTotals,omitempty"`

	WithholdingTax []*WithholdingTax `xml:"WithholdingTax,omitempty" json:"WithholdingTax,omitempty"`
}

type InvoiceStatus struct {

	// N para Normal, A anulado, F faturado, S Autofaturado

	InvoiceStatus string `xml:"InvoiceStatus,omitempty" json:"InvoiceStatus,omitempty"`

	InvoiceStatusDate time.Time `xml:"InvoiceStatusDate,omitempty" json:"InvoiceStatusDate,omitempty"`
}

type WorkStatus struct {

	// N para Normal, A anulado, F faturado

	WorkStatus string `xml:"WorkStatus,omitempty" json:"WorkStatus,omitempty"`

	WorkStatusDate time.Time `xml:"WorkStatusDate,omitempty" json:"WorkStatusDate,omitempty"`
}

type PaymentStatus struct {

	// N para Normal, A anulado

	PaymentStatus string `xml:"PaymentStatus,omitempty" json:"PaymentStatus,omitempty"`

	PaymentStatusDate time.Time `xml:"PaymentStatusDate,omitempty" json:"PaymentStatusDate,omitempty"`
}

type NewInvoiceStatusType struct {

	// N para Normal, A anulado, F faturado

	InvoiceStatus string `xml:"InvoiceStatus,omitempty" json:"InvoiceStatus,omitempty"`

	InvoiceStatusDate time.Time `xml:"InvoiceStatusDate,omitempty" json:"InvoiceStatusDate,omitempty"`
}

type NewWorkStatusType struct {

	// N para Normal, A anulado, F faturado

	WorkStatus string `xml:"WorkStatus,omitempty" json:"WorkStatus,omitempty"`

	WorkStatusDate time.Time `xml:"WorkStatusDate,omitempty" json:"WorkStatusDate,omitempty"`
}

type NewPaymentStatusType struct {

	// N para Normal, A anulado

	PaymentStatus string `xml:"PaymentStatus,omitempty" json:"PaymentStatus,omitempty"`

	PaymentStatusDate time.Time `xml:"PaymentStatusDate,omitempty" json:"PaymentStatusDate,omitempty"`
}

type SourceDocumentID struct {
	OriginatingON *OriginatingON `xml:"OriginatingON,omitempty" json:"OriginatingON,omitempty"`

	InvoiceDate *InvoiceDate `xml:"InvoiceDate,omitempty" json:"InvoiceDate,omitempty"`
}

type OrderReferences struct {
	OriginatingON *OriginatingON `xml:"OriginatingON,omitempty" json:"OriginatingON,omitempty"`

	OrderDate time.Time `xml:"OrderDate,omitempty" json:"OrderDate,omitempty"`
}

type Tax struct {
	TaxType *TaxType `xml:"TaxType,omitempty" json:"TaxType,omitempty"`

	TaxCountryRegion *TaxCountryRegion `xml:"TaxCountryRegion,omitempty" json:"TaxCountryRegion,omitempty"`

	TaxCode *TaxCode `xml:"TaxCode,omitempty" json:"TaxCode,omitempty"`

	TaxPercentage *PercentageType `xml:"TaxPercentage,omitempty" json:"TaxPercentage,omitempty"`

	TotalTaxAmount *MonetaryType `xml:"TotalTaxAmount,omitempty" json:"TotalTaxAmount,omitempty"`
}

type DocumentTotals struct {
	TaxPayable *MonetaryType `xml:"TaxPayable,omitempty" json:"TaxPayable,omitempty"`

	NetTotal *MonetaryType `xml:"NetTotal,omitempty" json:"NetTotal,omitempty"`

	GrossTotal *MonetaryType `xml:"GrossTotal,omitempty" json:"GrossTotal,omitempty"`
}

type WithholdingTax struct {
	WithholdingTaxType string `xml:"WithholdingTaxType,omitempty" json:"WithholdingTaxType,omitempty"`

	WithholdingTaxAmount *MonetaryType `xml:"WithholdingTaxAmount,omitempty" json:"WithholdingTaxAmount,omitempty"`
}

type DateRangeType struct {
	StartDate time.Time `xml:"StartDate,omitempty" json:"StartDate,omitempty"`

	EndDate time.Time `xml:"EndDate,omitempty" json:"EndDate,omitempty"`
}

type ListInvoiceDocumentsType struct {
	Invoice []*InvoiceHeaderType `xml:"invoice,omitempty" json:"invoice,omitempty"`
}

type ListWorkDocumentsType struct {
	Work []*WorkHeaderType `xml:"work,omitempty" json:"work,omitempty"`
}

type ListPaymentDocumentsType struct {
	Payment []*PaymentHeaderType `xml:"payment,omitempty" json:"payment,omitempty"`
}

type ResponseType struct {
	CodigoResposta int32 `xml:"CodigoResposta,omitempty" json:"CodigoResposta,omitempty"`

	Mensagem string `xml:"Mensagem,omitempty" json:"Mensagem,omitempty"`

	DataOperacao time.Time `xml:"DataOperacao,omitempty" json:"DataOperacao,omitempty"`
}

type ChannelType struct {
	Sistema string `xml:"Sistema,omitempty" json:"Sistema,omitempty"`

	Versao string `xml:"Versao,omitempty" json:"Versao,omitempty"`
}

type FatcorewsPort interface {
	RegisterInvoice(request *RegisterInvoiceRequest) (*RegisterInvoiceResponse, error)

	RegisterInvoiceContext(ctx context.Context, request *RegisterInvoiceRequest) (*RegisterInvoiceResponse, error)

	ChangeInvoiceStatus(request *ChangeInvoiceStatusRequest) (*ChangeInvoiceStatusResponse, error)

	ChangeInvoiceStatusContext(ctx context.Context, request *ChangeInvoiceStatusRequest) (*ChangeInvoiceStatusResponse, error)

	DeleteInvoice(request *DeleteInvoiceRequest) (*DeleteInvoiceResponse, error)

	DeleteInvoiceContext(ctx context.Context, request *DeleteInvoiceRequest) (*DeleteInvoiceResponse, error)

	RegisterWork(request *RegisterWorkRequest) (*RegisterWorkResponse, error)

	RegisterWorkContext(ctx context.Context, request *RegisterWorkRequest) (*RegisterWorkResponse, error)

	ChangeWorkStatus(request *ChangeWorkStatusRequest) (*ChangeWorkStatusResponse, error)

	ChangeWorkStatusContext(ctx context.Context, request *ChangeWorkStatusRequest) (*ChangeWorkStatusResponse, error)

	DeleteWork(request *DeleteWorkRequest) (*DeleteWorkResponse, error)

	DeleteWorkContext(ctx context.Context, request *DeleteWorkRequest) (*DeleteWorkResponse, error)

	RegisterPayment(request *RegisterPaymentRequest) (*RegisterPaymentResponse, error)

	RegisterPaymentContext(ctx context.Context, request *RegisterPaymentRequest) (*RegisterPaymentResponse, error)

	ChangePaymentStatus(request *ChangePaymentStatusRequest) (*ChangePaymentStatusResponse, error)

	ChangePaymentStatusContext(ctx context.Context, request *ChangePaymentStatusRequest) (*ChangePaymentStatusResponse, error)

	DeletePayment(request *DeletePaymentRequest) (*DeletePaymentResponse, error)

	DeletePaymentContext(ctx context.Context, request *DeletePaymentRequest) (*DeletePaymentResponse, error)
}

type fatcorewsPort struct {
	client *soap.Client
}

func NewFatcorewsPort(client *soap.Client) FatcorewsPort {
	return &fatcorewsPort{
		client: client,
	}
}

func (service *fatcorewsPort) RegisterInvoiceContext(ctx context.Context, request *RegisterInvoiceRequest) (*RegisterInvoiceResponse, error) {
	response := new(RegisterInvoiceResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) RegisterInvoice(request *RegisterInvoiceRequest) (*RegisterInvoiceResponse, error) {
	return service.RegisterInvoiceContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) ChangeInvoiceStatusContext(ctx context.Context, request *ChangeInvoiceStatusRequest) (*ChangeInvoiceStatusResponse, error) {
	response := new(ChangeInvoiceStatusResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) ChangeInvoiceStatus(request *ChangeInvoiceStatusRequest) (*ChangeInvoiceStatusResponse, error) {
	return service.ChangeInvoiceStatusContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) DeleteInvoiceContext(ctx context.Context, request *DeleteInvoiceRequest) (*DeleteInvoiceResponse, error) {
	response := new(DeleteInvoiceResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) DeleteInvoice(request *DeleteInvoiceRequest) (*DeleteInvoiceResponse, error) {
	return service.DeleteInvoiceContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) RegisterWorkContext(ctx context.Context, request *RegisterWorkRequest) (*RegisterWorkResponse, error) {
	response := new(RegisterWorkResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) RegisterWork(request *RegisterWorkRequest) (*RegisterWorkResponse, error) {
	return service.RegisterWorkContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) ChangeWorkStatusContext(ctx context.Context, request *ChangeWorkStatusRequest) (*ChangeWorkStatusResponse, error) {
	response := new(ChangeWorkStatusResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) ChangeWorkStatus(request *ChangeWorkStatusRequest) (*ChangeWorkStatusResponse, error) {
	return service.ChangeWorkStatusContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) DeleteWorkContext(ctx context.Context, request *DeleteWorkRequest) (*DeleteWorkResponse, error) {
	response := new(DeleteWorkResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) DeleteWork(request *DeleteWorkRequest) (*DeleteWorkResponse, error) {
	return service.DeleteWorkContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) RegisterPaymentContext(ctx context.Context, request *RegisterPaymentRequest) (*RegisterPaymentResponse, error) {
	response := new(RegisterPaymentResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) RegisterPayment(request *RegisterPaymentRequest) (*RegisterPaymentResponse, error) {
	return service.RegisterPaymentContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) ChangePaymentStatusContext(ctx context.Context, request *ChangePaymentStatusRequest) (*ChangePaymentStatusResponse, error) {
	response := new(ChangePaymentStatusResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) ChangePaymentStatus(request *ChangePaymentStatusRequest) (*ChangePaymentStatusResponse, error) {
	return service.ChangePaymentStatusContext(
		context.Background(),
		request,
	)
}

func (service *fatcorewsPort) DeletePaymentContext(ctx context.Context, request *DeletePaymentRequest) (*DeletePaymentResponse, error) {
	response := new(DeletePaymentResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *fatcorewsPort) DeletePayment(request *DeletePaymentRequest) (*DeletePaymentResponse, error) {
	return service.DeletePaymentContext(
		context.Background(),
		request,
	)
}
