// Code generated by gowsdl DO NOT EDIT.

package seriesws

import (
	"context"
	"encoding/xml"
	"time"

	"github.com/hooklift/gowsdl/soap"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type SerieType string

type TipoSerieType string

type ClasseDocType string

type TipoDocType string

type NumSeqType int32

type NumCertSWFaturType int32

type CodValidacaoSerieType string

type MotivoType string

type JustificacaoType string

type EstadoType string

type CodResultOperType int32

type MsgResultOperType string

type NifType string

type MeioProcessamentoType string

type AnularSerie struct {
	XMLName xml.Name `xml:"at:anularSerie"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	// Indique o identificador da Série cuja comunicação pretende anular.
	Serie *SerieType `xml:"serie,omitempty" json:"serie,omitempty"`

	// Indique a classificação dada ao documento a que pertence a Série cuja comunicação pretende anular.
	ClasseDoc *ClasseDocType `xml:"classeDoc,omitempty" json:"classeDoc,omitempty"`

	// Indique o tipo de documento a que pertence a Série cuja comunicação pretende anular.
	TipoDoc *TipoDocType `xml:"tipoDoc,omitempty" json:"tipoDoc,omitempty"`

	// Indique o código de validação da série, atribuído pela AT, cuja comunicação pretende anular.
	CodValidacaoSerie *CodValidacaoSerieType `xml:"codValidacaoSerie,omitempty" json:"codValidacaoSerie,omitempty"`

	// Indique o motivo pelo qual pretende anular a comunicação da Série.
	Motivo *MotivoType `xml:"motivo,omitempty" json:"motivo,omitempty"`

	// Indicação informativa de que o sujeito passivo teve conhecimento de que não deve anular a comunicação de uma Série se já utilizou documentos emitidos com a informação da mesma. A comunicação não será aceite se o sujeito passivo não indicar (preenchendo com o valor verdadeiro este parâmetro) que teve conhecimento da condição apresentada.
	DeclaracaoNaoEmissao bool `xml:"declaracaoNaoEmissao,omitempty" json:"declaracaoNaoEmissao,omitempty"`
}

type AnularSerieResponse struct {
	XMLName xml.Name `xml:"anularSerieResponse"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	AnularSerieResp *SeriesResp `xml:"anularSerieResp,omitempty" json:"anularSerieResp,omitempty"`
}

type ConsultarSeries struct {
	XMLName xml.Name `xml:"at:consultarSeries"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	// Indique o identificador da Série que pretende consultar.
	Serie *SerieType `xml:"serie,omitempty" json:"serie,omitempty"`

	// Indique o tipo da Série que pretende consultar.
	TipoSerie *TipoSerieType `xml:"tipoSerie,omitempty" json:"tipoSerie,omitempty"`

	// Indique a classificação dada ao documento a que pertence a Série que pretende consultar.
	ClasseDoc *ClasseDocType `xml:"classeDoc,omitempty" json:"classeDoc,omitempty"`

	// Indique o tipo de documento a que pertence a Série que pretende consultar.
	TipoDoc *TipoDocType `xml:"tipoDoc,omitempty" json:"tipoDoc,omitempty"`

	// Indique o código de validação da Série, atribuído pela AT, que pretende consultar.
	CodValidacaoSerie *CodValidacaoSerieType `xml:"codValidacaoSerie,omitempty" json:"codValidacaoSerie,omitempty"`

	// Indique a data inicial do intervalo de pesquisa.
	DataRegistoDe soap.XSDDate `xml:"dataRegistoDe,omitempty" json:"dataRegistoDe,omitempty"`

	// Indique a data final do intervalo de pesquisa.
	DataRegistoAte soap.XSDDate `xml:"dataRegistoAte,omitempty" json:"dataRegistoAte,omitempty"`

	// Indique o estado da Série que pretende consultar.
	Estado *EstadoType `xml:"estado,omitempty" json:"estado,omitempty"`

	// Código de meio de processamento dos documentos a emitir.
	MeioProcessamento *MeioProcessamentoType `xml:"meioProcessamento,omitempty" json:"meioProcessamento,omitempty"`
}

type ConsultarSeriesResponse struct {
	XMLName xml.Name `xml:"consultarSeriesResponse"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	ConsultarSeriesResp *ConsultSeriesResp `xml:"consultarSeriesResp,omitempty" json:"consultarSeriesResp,omitempty"`
}

type FinalizarSerie struct {
	XMLName xml.Name `xml:"at:finalizarSerie"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	// Indique o identificador da Série que pretende finalizar.
	Serie *SerieType `xml:"serie,omitempty" json:"serie,omitempty"`

	// Indique a classificação dada ao documento a que pertence a Série que pretende finalizar.
	ClasseDoc *ClasseDocType `xml:"classeDoc,omitempty" json:"classeDoc,omitempty"`

	// Indique o tipo de documento a que pertence a Série que pretende finalizar.
	TipoDoc *TipoDocType `xml:"tipoDoc,omitempty" json:"tipoDoc,omitempty"`

	// Indique o código de validação da série, atribuído pela AT, que pretende finalizar.
	CodValidacaoSerie *CodValidacaoSerieType `xml:"codValidacaoSerie,omitempty" json:"codValidacaoSerie,omitempty"`

	// Indique o número do último documento emitido da Série que pretende finalizar.
	SeqUltimoDocEmitido *NumSeqType `xml:"seqUltimoDocEmitido,omitempty" json:"seqUltimoDocEmitido,omitempty"`

	// Indique observações pertinentes à finalização da Série.
	Justificacao *JustificacaoType `xml:"justificacao,omitempty" json:"justificacao,omitempty"`
}

type FinalizarSerieResponse struct {
	XMLName xml.Name `xml:"finalizarSerieResponse"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	FinalizarSerieResp *SeriesResp `xml:"finalizarSerieResp,omitempty" json:"finalizarSerieResp,omitempty"`
}

type RegistarSerie struct {
	XMLName xml.Name `xml:"at:registarSerie"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	// Indique o identificador da Série que pretende comunicar a AT.
	Serie *SerieType `xml:"serie,omitempty" json:"serie,omitempty"`

	// Indique o tipo da Série que pretende comunicar a AT.
	TipoSerie *TipoSerieType `xml:"tipoSerie,omitempty" json:"tipoSerie,omitempty"`

	// Indique a classificação dada ao documento a que pertence a Série a comunicar à AT.
	ClasseDoc *ClasseDocType `xml:"classeDoc,omitempty" json:"classeDoc,omitempty"`

	// Indique o tipo de documento a que pertence a Série a comunicar à AT.
	TipoDoc *TipoDocType `xml:"tipoDoc,omitempty" json:"tipoDoc,omitempty"`

	// Indique o início da numeração de sequência do documento na Série.
	NumInicialSeq *NumSeqType `xml:"numInicialSeq,omitempty" json:"numInicialSeq,omitempty"`

	// Indique a data a partir da qual se prevê a utilização da Série.
	DataInicioPrevUtiliz soap.XSDDate `xml:"dataInicioPrevUtiliz,omitempty" json:"dataInicioPrevUtiliz,omitempty"`

	// Indique o número do certificado do programa de faturação, atribuído pela AT. Se não aplicável, deve ser preenchido com "0" (zero).
	NumCertSWFatur *NumCertSWFaturType `xml:"numCertSWFatur,omitempty" json:"numCertSWFatur,omitempty"`

	// Código de meio de processamento dos documentos a emitir.
	MeioProcessamento *MeioProcessamentoType `xml:"meioProcessamento,omitempty" json:"meioProcessamento,omitempty"`
}

type RegistarSerieResponse struct {
	XMLName xml.Name `xml:"registarSerieResponse"`
	XmlNSAt string   `xml:"xmlns:at,attr"`

	RegistarSerieResp *SeriesResp `xml:"registarSerieResp,omitempty" json:"registarSerieResp,omitempty"`
}

type SeriesResp struct {
	XmlNSAt string `xml:"xmlns:at,attr"`

	InfoSerie *SeriesInfo `xml:"infoSerie,omitempty" json:"infoSerie,omitempty"`

	InfoResultOper *OperationResultInfo `xml:"infoResultOper,omitempty" json:"infoResultOper,omitempty"`
}

type SeriesInfo struct {
	XmlNSAt string `xml:"xmlns:at,attr"`

	// Identificador da Série.
	Serie *SerieType `xml:"serie,omitempty" json:"serie,omitempty"`

	// Código do tipo da Série.
	TipoSerie *TipoSerieType `xml:"tipoSerie,omitempty" json:"tipoSerie,omitempty"`

	// Código da classificação dada ao documento a que pertence a Série.
	ClasseDoc *ClasseDocType `xml:"classeDoc,omitempty" json:"classeDoc,omitempty"`

	// Código do tipo de documento da Série.
	TipoDoc *TipoDocType `xml:"tipoDoc,omitempty" json:"tipoDoc,omitempty"`

	// Início da numeração de sequência do documento na Série.
	NumInicialSeq *NumSeqType `xml:"numInicialSeq,omitempty" json:"numInicialSeq,omitempty"`

	// Fim da numeração de sequência do documento na Série.
	NumFinalSeq *NumSeqType `xml:"numFinalSeq,omitempty" json:"numFinalSeq,omitempty"`

	// Data a partir da qual se prevê a utilização da Série.
	DataInicioPrevUtiliz soap.XSDDate `xml:"dataInicioPrevUtiliz,omitempty" json:"dataInicioPrevUtiliz,omitempty"`

	// Sequência do último documento emitido da Série.
	SeqUltimoDocEmitido *NumSeqType `xml:"seqUltimoDocEmitido,omitempty" json:"seqUltimoDocEmitido,omitempty"`

	// Código de meio de processamento dos documentos a emitir.
	MeioProcessamento *MeioProcessamentoType `xml:"meioProcessamento,omitempty" json:"meioProcessamento,omitempty"`

	// Número do certificado do programa de faturação, atribuído pela AT. Se não aplicável, o resultado é preenchido com "0" (zero).
	NumCertSWFatur *NumCertSWFaturType `xml:"numCertSWFatur,omitempty" json:"numCertSWFatur,omitempty"`

	// Código de validação da Série, atribuído pela AT.
	CodValidacaoSerie *CodValidacaoSerieType `xml:"codValidacaoSerie,omitempty" json:"codValidacaoSerie,omitempty"`

	// Data do registo da Série.
	DataRegisto soap.XSDDate `xml:"dataRegisto,omitempty" json:"dataRegisto,omitempty"`

	// Código do estado que a Série possui no decorrer do processo de comunicação.
	Estado *EstadoType `xml:"estado,omitempty" json:"estado,omitempty"`

	// Código de motivo justificativo da mudança de estado.
	MotivoEstado *MotivoType `xml:"motivoEstado,omitempty" json:"motivoEstado,omitempty"`

	// Observações pertinentes comunicadas sobre a finalização da Série.
	Justificacao *JustificacaoType `xml:"justificacao,omitempty" json:"justificacao,omitempty"`

	// Data da última alteração de estado da Série.
	DataEstado soap.XSDDateTime `xml:"dataEstado,omitempty" json:"dataEstado,omitempty"`

	// Número fiscal do contribuinte responsável pela comunicação da Série.
	NifComunicou *NifType `xml:"nifComunicou,omitempty" json:"nifComunicou,omitempty"`
}

type OperationResultInfo struct {
	XmlNSAt string `xml:"xmlns:at,attr"`

	// Código do resultado da operação
	CodResultOper *CodResultOperType `xml:"codResultOper,omitempty" json:"codResultOper,omitempty"`

	// Mensagem do resultado da operação
	MsgResultOper *MsgResultOperType `xml:"msgResultOper,omitempty" json:"msgResultOper,omitempty"`
}

type ConsultSeriesResp struct {
	XmlNSAt string `xml:"xmlns:at,attr"`

	InfoSerie []*SeriesInfo `xml:"infoSerie,omitempty" json:"infoSerie,omitempty"`

	InfoResultOper *OperationResultInfo `xml:"infoResultOper,omitempty" json:"infoResultOper,omitempty"`
}

type SeriesWS interface {

	/*
	   Esta funcionalidade tem como objetivo, permitir a comunicação das séries à AT, através do
	   registo das mesmas, de modo a que seja atribuído um código único de validação da série.
	*/
	RegistarSerie(request *RegistarSerie) (*RegistarSerieResponse, error)

	RegistarSerieContext(ctx context.Context, request *RegistarSerie) (*RegistarSerieResponse, error)

	/*
	   Esta funcionalidade tem como objetivo, indicar que uma série foi válida para um conjunto
	   de documentos, mas que a mesma já não será usada a partir do último documento comunicado.
	*/
	FinalizarSerie(request *FinalizarSerie) (*FinalizarSerieResponse, error)

	FinalizarSerieContext(ctx context.Context, request *FinalizarSerie) (*FinalizarSerieResponse, error)

	/*
	   Esta funcionalidade tem como objetivo, disponibilizar a consulta das séries comunicadas.
	*/
	ConsultarSeries(request *ConsultarSeries) (*ConsultarSeriesResponse, error)

	ConsultarSeriesContext(ctx context.Context, request *ConsultarSeries) (*ConsultarSeriesResponse, error)

	/*
	   Esta funcionalidade tem como objetivo, disponibilizar a ação de anular a comunicação
	   de uma série anteriormente comunicada, por erro.
	*/
	AnularSerie(request *AnularSerie) (*AnularSerieResponse, error)

	AnularSerieContext(ctx context.Context, request *AnularSerie) (*AnularSerieResponse, error)
}

type seriesWS struct {
	client *soap.Client
}

func NewSeriesWS(client *soap.Client) SeriesWS {
	return &seriesWS{
		client: client,
	}
}

func (service *seriesWS) RegistarSerieContext(ctx context.Context, request *RegistarSerie) (*RegistarSerieResponse, error) {
	request.XmlNSAt = "http://at.gov.pt/"
	response := new(RegistarSerieResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *seriesWS) RegistarSerie(request *RegistarSerie) (*RegistarSerieResponse, error) {
	return service.RegistarSerieContext(
		context.Background(),
		request,
	)
}

func (service *seriesWS) FinalizarSerieContext(ctx context.Context, request *FinalizarSerie) (*FinalizarSerieResponse, error) {
	request.XmlNSAt = "http://at.gov.pt/"
	response := new(FinalizarSerieResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *seriesWS) FinalizarSerie(request *FinalizarSerie) (*FinalizarSerieResponse, error) {
	return service.FinalizarSerieContext(
		context.Background(),
		request,
	)
}

func (service *seriesWS) ConsultarSeriesContext(ctx context.Context, request *ConsultarSeries) (*ConsultarSeriesResponse, error) {
	request.XmlNSAt = "http://at.gov.pt/"
	response := new(ConsultarSeriesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *seriesWS) ConsultarSeries(request *ConsultarSeries) (*ConsultarSeriesResponse, error) {
	return service.ConsultarSeriesContext(
		context.Background(),
		request,
	)
}

func (service *seriesWS) AnularSerieContext(ctx context.Context, request *AnularSerie) (*AnularSerieResponse, error) {
	request.XmlNSAt = "http://at.gov.pt/"
	response := new(AnularSerieResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *seriesWS) AnularSerie(request *AnularSerie) (*AnularSerieResponse, error) {
	return service.AnularSerieContext(
		context.Background(),
		request,
	)
}
