package errcodes

import "errors"

// UQ = Unique Constraint
// KR = Key Reference
var (
	ErrUQAccountId                  = errors.New("saft: unique constraint violation - account id")
	ErrUQCustomerId                 = errors.New("saft: unique constraint violation - customer id")
	ErrUQSupplierId                 = errors.New("saft: unique constraint violation - supplier id")
	ErrUQProductCode                = errors.New("saft: unique constraint violation - product code")
	ErrUQJournalId                  = errors.New("saft: unique constraint violation - journal id")
	ErrUQTransactionId              = errors.New("saft: unique constraint violation - transaction id")
	ErrUQInvoiceNo                  = errors.New("saft: unique constraint violation - invoice no")
	ErrUQDocumentNo                 = errors.New("saft: unique constraint violation - document no")
	ErrUQWorkDocNo                  = errors.New("saft: unique constraint violation - work document no")
	ErrUQPaymentRefNo               = errors.New("saft: unique constraint violation - payment ref no")
	ErrKRGenLedgerAccountsAccountID = errors.New("saft: key reference violation - general ledger entries account id")
	ErrKRGenLedgerEntriesSupplierID = errors.New("saft: key reference violation - general ledger entries supplier id")
	ErrKRGenLedgerEntriesAccountID  = errors.New("saft: key reference violation - general ledger entries account id")
	ErrKRGenLedgerEntriesCustomerID = errors.New("saft: key reference violation - general ledger entries customer id")
	ErrKRInvoiceCustomerID          = errors.New("saft: key reference violation - invoice customer id")
	ErrKRInvoiceProductCode         = errors.New("saft: key reference violation - invoice product code")
	ErrKRStockMovementCustomerID    = errors.New("saft: key reference violation - stock movement customer id")
	ErrKRStockMovementSupplierID    = errors.New("saft: key reference violation - stock movement supplier id")
	ErrKRStockMovementProductCode   = errors.New("saft: key reference violation - stock movement product code")
	ErrKRWorkDocumentCustomerID     = errors.New("saft: key reference violation - work document customer id")
	ErrKRWorkDocumentProductCode    = errors.New("saft: key reference violation - work document product code")
	ErrKRPaymentCustomerID          = errors.New("saft: key reference violation - payment customer id")
	ErrValidationAccountId          = errors.New("saft: account id validation error")
	ErrCashVatschemeIndicator       = errors.New("saft: cash vat scheme indicator validation error")
)

// Other errors
var (
	ErrGroupingCategoryTaxonomyCode = errors.New("saft: grouping category GM and taxonomy code must be present together")
	ErrGroupingCategoryGroupingCode = errors.New("saft: invalid grouping category and grouping code combination")
)

// Header Errors
var (
	ErrUnsupportedSAFTVersion     = errors.New("saft: unsupported SAFT version")
	ErrCompanyId                  = errors.New("saft: company id missing or invalid")
	ErrInvalidSaftType            = errors.New("saft: invalid saft type")
	ErrEmptyCompanyName           = errors.New("saft: company name is empty")
	ErrEmptyCompanyAddress        = errors.New("saft: company address is empty")
	ErrEmptyAddressDetail         = errors.New("saft: address detail is empty")
	ErrEmptyCity                  = errors.New("saft: city is empty")
	ErrEmptyPostalCode            = errors.New("saft: postal code is empty")
	ErrEmptyCountry               = errors.New("saft: country is empty")
	ErrInvalidCountry             = errors.New("saft: country is invalid")
	ErrInvalidFiscalYear          = errors.New("saft: fiscal year missing or invalid")
	ErrInvalidStartDate           = errors.New("saft: start date missing or invalid")
	ErrInvalidEndDate             = errors.New("saft: end date missing or invalid")
	ErrInvalidDateSpan            = errors.New("saft: span date invalid")
	ErrCurrencyNotEuro            = errors.New("saft: currency is not EUR")
	ErrMissingDateCreated         = errors.New("saft: date created is missing")
	ErrMissingTaxEntity           = errors.New("saft: tax entity is missing, muste be Global, Sede or the establishment name")
	ErrMissingProductCompanyTaxId = errors.New("saft: product company tax id is missing")
	ErrInvalidProductId           = errors.New("saft: product id is invalid")
	ErrMissingProductVersion      = errors.New("saft: product version is missing")
)

// Customer Errors
var (
	ErrMissingCustomerID           = errors.New("saft: customer id is missing, muste be Desconhecido or a string")
	ErrMissingAccountID            = errors.New("missing account ID")
	ErrMissingCustomerTaxID        = errors.New("missing customer tax ID")
	ErrInvalidCustomerTaxID        = errors.New("invalid customer tax ID")
	ErrMissingCompanyName          = errors.New("missing company name")
	ErrMissingBillingAddress       = errors.New("missing billing address")
	ErrMissingAddressDetail        = errors.New("missing address detail")
	ErrMissingCity                 = errors.New("missing city")
	ErrMissingPostalCode           = errors.New("missing postal code")
	ErrMissingCountry              = errors.New("missing country")
	ErrInvalidSelfBillingIndicator = errors.New("invalid self-billing indicator")
)

// Payment Errors
var (
	ErrMissingPaymentLine                        = errors.New("saft: missing payment line")
	ErrDebitCreditAmount                         = errors.New("saft: cannot have both debit and credit amount")
	ErrPaymentNumberOfEntries                    = errors.New("saft: wrong number of entries in payment")
	ErrPaymentTotalCredit                        = errors.New("saft: total credit amount does not match")
	ErrPaymentTotalDebit                         = errors.New("saft: total debit amount does not match")
	ErrMissingPaymentRefNo                       = errors.New("saft: missing payment reference number")
	ErrMissingPaymentATCUD                       = errors.New("saft: missing payment ATCUD")
	ErrMissingPaymentTransactionDate             = errors.New("saft: missing payment transaction date")
	ErrInvalidPaymentTransactionDate             = errors.New("saft: invalid payment transaction date")
	ErrInvalidPaymentType                        = errors.New("saft: invalid payment type")
	ErrMissingPaymentDocumentStatus              = errors.New("saft: missing payment document status")
	ErrInvalidPaymentStatus                      = errors.New("saft: invalid payment status")
	ErrKRPaymentTransactionId                    = errors.New("saft: key reference violation - payment transaction id")
	ErrMissingPaymentDocumentStatusDate          = errors.New("saft: missing payment document status date")
	ErrInvalidPaymentDocumentStatusDate          = errors.New("saft: invalid payment document status date")
	ErrMissingPaymentDocumentStatusSourceId      = errors.New("saft: missing payment document status source id")
	ErrInvalidPaymentDocumentStatusSourcePayment = errors.New("saft: invalid payment document status source payment")
	ErrMissingPaymentMethod                      = errors.New("saft: missing payment method")
	ErrInvalidPaymentMechanism                   = errors.New("saft: invalid payment mechanism")
	ErrPaymentAmount                             = errors.New("saft: payment amount does not match")
	ErrInvalidPaymentDate                        = errors.New("saft: invalid payment date")
	ErrMissingPaymentSourceId                    = errors.New("saft: missing payment source id")
	ErrMissingPaymentCustomerID                  = errors.New("saft: missing payment customer id")
	ErrPaymentLineSourceDocumentId               = errors.New("saft: missing source document id, minimum 1 ")
	ErrPaymentLineSourceDocumentIdOriginatingOn  = errors.New("saft: missing origination on, on Payment Line")
	ErrPaymentLineTax                            = errors.New("saft: missing tax, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxType                        = errors.New("saft: missing tax type, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxCountryRegion               = errors.New("saft: missing tax country region, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxPercentageAmount            = errors.New("saft: missing tax percentage amount, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxPercentage                  = errors.New("saft: missing or invalid tax percentage, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxAmount                      = errors.New("saft: missing tax amount, on Payment Line due to Payment Type RC")
	ErrPaymentLineTaxTaxExemption                = errors.New("saft: cant have tax and Tax exemption on Payment Line")
)
